# Generated by Django 4.2.1 on 2023-05-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_alter_categoria_descripcion_alter_marca_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
