# Generated by Django 4.2.1 on 2023-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_inventario_fecha_vencimiento_alter_marca_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='fecha_venta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
