# Generated by Django 4.2.1 on 2023-05-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_alter_detalleventa_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='fecha_venta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
